### ISSUE TITLE
update code vars and  comments

### ISSUE THREAD

**Issue by bunnyblue** [bunnyblue/AtlasForAndroid#100]
update code vars

**Comment by bboyfeiyu** [comment]
@bunnyblue 淘宝的 ？另外希望文档补全一些哈 ~ :+1:

**Comment by bunnyblue** [comment]
No~，just looks  like，文档努力整理中

**Comment by bboyfeiyu** [comment]
那你怎么找到了Atlas的代码呢 ？:)

**Comment by bunnyblue** [comment]
文档和架构正在整理中，感兴趣的内心等下，也欢迎参与

**Comment by bboyfeiyu** [comment]
@bunnyblue 跟atlas基本上一致呐

**Comment by bunnyblue** [comment]
等你贡献代码，要做的东西可能还有很多

**Comment by bboyfeiyu** [comment]
@bunnyblue 对于osgi目前还不了解，最近也比较忙，我看看有时间参与一下。:)

**Comment by ownwell** [comment]
必须赞一个

**Comment by bunnyblue** [comment]
OSGI的文档可以参考下http://wenku.baidu.com/link?url=ZrxarWXev0AWWpnTbStdS90bD4-cm4ApQ3TfjaqacMy484llxJ8jrI6ezoGuKjv2qI-mQgBvqGtltb7SFn8Vr6UaaTUMz3bEsvdRuIsW76S  有别的欢迎补充

**Comment by weiyihz** [comment]
必须赞！喜欢

**Comment by bunnyblue** [comment]
目前正在进行稳定性和兼容性测试

**Comment by mejonzhan** [comment]
java.lang.RuntimeException: Unable to instantiate application com.openatlas.launcher.BootApp: java.lang.ClassNotFoundException: Didn't find class "com.openatlas.launcher.BootApp" on path: DexPathList[[zip file "/data/app/com.openatlas.launcher-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.openatlas.launcher-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3885):        at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
E/AndroidRuntime( 3885):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4395)
E/AndroidRuntime( 3885):        at android.app.ActivityThread.access$1500(ActivityThread.java:140)
E/AndroidRuntime( 3885):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
E/AndroidRuntime( 3885):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3885):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3885):        at android.app.ActivityThread.main(ActivityThread.java:5098)
E/AndroidRuntime( 3885):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3885):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3885):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
E/AndroidRuntime( 3885):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
E/AndroidRuntime( 3885):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3885): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.openatlas.launcher.BootApp" on path: DexPathList[[zip file "/data/app/com.openatlas.launcher-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.openatlas.launcher-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3885):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 3885):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 3885):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 3885):        at android.app.Instrumentation.newApplication(Instrumentation.java:977)
E/AndroidRuntime( 3885):        at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
E/AndroidRuntime( 3885):        ... 11 more

**Comment by mejonzhan** [comment]
为啥demo都跑不起来呢？另外，看到宿主程序中有插件的activity的声名，是真的么？那这个插件就很不灵活了；想在插件中加个activity，然后在线更新一下，那还得更新宿主程序

**Comment by bunnyblue** [comment]
对 ，需要声明，没用代理，所有需要声明

**Comment by bunnyblue** [comment]
update :testing
