### ISSUE TITLE
android.content.res.Resources$NotFoundException: 

### ISSUE THREAD

**Issue by bunnyblue** [bunnyblue/AtlasForAndroid#26]
03-28 16:45:29.450: W/System.err(17251): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taobao.taobao/com.taobao.android.gamecenter.main.ActivityInternalActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f030001
03-28 16:45:29.450: W/System.err(17251): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
03-28 16:45:29.450: W/System.err(17251): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2328)

**Comment by bunnyblue** [comment]
TypedValue{t=0x3/d=0x25c "res/drawable/screen_background_selector_light.xml" a=1 r=0x1080528}
0x7f030001指向的文件错了

**Comment by bunnyblue** [comment]
0x7f030000 (2130903040) = layout.abc_action_bar_decor: res/layout/abc_action_bar_decor.xml
  0x7f030001 (2130903041) = layout.abc_action_bar_decor_include: res/layout/abc_action_bar_decor_include.xml
  0x7f030002 (2130903042) = layout.abc_action_bar_decor_overlay: res/layout/abc_action_bar_decor_overlay.xml
  0x7f030003 (2130903043) = layout.abc_action_bar_decor_overlay_taobao: res/layout/abc_action_bar_decor_overlay_taobao.xml
  0x7f030004 (2130903044) = layout.abc_action_bar_decor_taobao: res/layout/abc_action_bar_decor_taobao.xml
  0x7f030005 (2130903045) = layout.abc_action_bar_home: res/layout/abc_action_bar_home.xml
  0x7f030006 (2130903046) = layout.abc_action_bar_tab: res/layout/abc_action_bar_tab.xml
  0x7f030007 (2130903047) = layout.abc_action_bar_tabbar: res/layout/abc_action_bar_tabbar.xml
  0x7f030008 (2130903048) = layout.abc_action_bar_title_item: res/layout/abc_action_bar_title_item.xml
  0x7f030009 (2130903049) = layout.abc_action_bar_view_list_nav_layout: res/layout/abc_action_bar_view_list_nav_layout.xml
  0x7f03000a (2130903050) = layout.abc_action_menu_item_layout: res/layout/abc_action_menu_item_layout.xml
  0x7f03000b (2130903051) = layout.abc_action_menu_layout: res/layout/abc_action_menu_layout.xml
  0x7f03000c (2130903052) = layout.abc_action_mode_bar: res/layout/abc_action_mode_bar.xml
  0x7f03000d (2130903053) = layout.abc_action_mode_close_item: res/layout/abc_action_mode_close_item.xml
  0x7f03000e (2130903054) = layout.abc_activity_chooser_view: res/layout/abc_activity_chooser_view.xml
  0x7f03000f (2130903055) = layout.abc_activity_chooser_view_include: res/layout/abc_activity_chooser_view_include.xml
  0x7f030010 (2130903056) = layout.abc_activity_chooser_view_list_item: res/layout/abc_activity_chooser_view_list_item.xml
  0x7f030011 (2130903057) = layout.abc_container_layout: res/layout/abc_container_layout.xml
  0x7f030012 (2130903058) = layout.abc_expanded_menu_layout: res/layout/abc_expanded_menu_layout.xml
  0x7f030013 (2130903059) = layout.abc_list_menu_item_checkbox: res/layout/abc_list_menu_item_checkbox.xml
  0x7f030014 (2130903060) = layout.abc_list_menu_item_icon: res/layout/abc_list_menu_item_icon.xml
  0x7f030015 (2130903061) = layout.abc_list_menu_item_layout: res/layout/abc_list_menu_item_layout.xml
  0x7f030016 (2130903062) = layout.abc_list_menu_item_radio: res/layout/abc_list_menu_item_radio.xml
  0x7f030017 (2130903063) = layout.abc_list_menu_item_text_icon: res/layout/abc_list_menu_item_text_icon.xml
  0x7f030018 (2130903064) = layout.abc_list_menu_item_tip: res/layout/abc_list_menu_item_tip.xml
  0x7f030019 (2130903065) = layout.abc_list_menu_item_tip_nonum: res/layout/abc_list_menu_item_tip_nonum.xml
  0x7f03001a (2130903066) = layout.abc_popup_menu_item_layout: res/layout/abc_popup_menu_item_layout.xml
  0x7f03001b (2130903067) = layout.abc_search_dropdown_item_icons_2line: res/layout/abc_search_dropdown_item_icons_2line.xml
  0x7f03001c (2130903068) = layout.abc_search_view: res/layout/abc_search_view.xml
  0x7f03001d (2130903069) = layout.activity_bundle_not_found: res/layout/activity_bundle_not_found.xml
  0x7f03001e (2130903070) = layout.activity_main: res/layout/activity_main.xml
  0x7f03001f (2130903071) = layout.activity_navigation_bar: res/layout/activity_navigation_bar.xml
  0x7f030020 (2130903072) = layout.activity_safemode: res/layout/activity_safemode.xml
  0x7f030021 (2130903073) = layout.activity_space: res/layout/activity_space.xml
  0x7f030022 (2130903074) = layout.authorization_page: res/layout/authorization_page.xml
  0x7f030023 (2130903075) = layout.banner_item: res/layout/banner_item.xml
  0x7f030024 (2130903076) = layout.barrier_detail_main: res/layout/barrier_detail_main.xml
  0x7f030025 (2130903077) = layout.bundle_wait: res/layout/bundle_wait.xml
  0x7f030026 (2130903078) = layout.connecterror_layout: res/layout/connecterror_layout.xml
  0x7f030027 (2130903079) = layout.empty_bg_layout: res/layout/empty_bg_layout.xml
  0x7f030028 (2130903080) = layout.fragment_navigation_bar: res/layout/fragment_navigation_bar.xml
  0x7f030029 (2130903081) = layout.gallary_viewpage: res/layout/gallary_viewpage.xml
  0x7f03002a (2130903082) = layout.limit_11_view: res/layout/limit_11_view.xml
  0x7f03002b (2130903083) = layout.limit_default_view: res/layout/limit_default_view.xml
  0x7f03002c (2130903084) = layout.list_item_bundle_list: res/layout/list_item_bundle_list.xml
  0x7f03002d (2130903085) = layout.loading_mask_layout: res/layout/loading_mask_layout.xml
  0x7f03002e (2130903086) = layout.loading_mask_layout_transparent: res/layout/loading_mask_layout_transparent.xml
  0x7f03002f (2130903087) = layout.login_new_member: res/layout/login_new_member.xml
  0x7f030030 (2130903088) = layout.main: res/layout/main.xml
  0x7f030031 (2130903089) = layout.navigation_bar_icon: res/layout/navigation_bar_icon.xml
  0x7f030032 (2130903090) = layout.open_oauth_list_footer: res/layout/open_oauth_list_footer.xml
  0x7f030033 (2130903091) = layout.open_oauth_list_item: res/layout/open_oauth_list_item.xml
  0x7f030034 (2130903092) = layout.scene1_1: res/layout/scene1_1.xml
  0x7f030035 (2130903093) = layout.scene1_2: res/layout/scene1_2.xml
  0x7f030036 (2130903094) = layout.scene2_1: res/layout/scene2_1.xml
  0x7f030037 (2130903095) = layout.scene2_2: res/layout/scene2_2.xml
  0x7f030038 (2130903096) = layout.scene2_3: res/layout/scene2_3.xml
  0x7f030039 (2130903097) = layout.scene3_1: res/layout/scene3_1.xml
  0x7f03003a (2130903098) = layout.scene4_1: res/layout/scene4_1.xml
  0x7f03003b (2130903099) = layout.scene4_2: res/layout/scene4_2.xml
  0x7f03003c (2130903100) = layout.scene4_3: res/layout/scene4_3.xml
  0x7f03003d (2130903101) = layout.scene4_4: res/layout/scene4_4.xml
  0x7f03003e (2130903102) = layout.scene5_1: res/layout/scene5_1.xml
  0x7f03003f (2130903103) = layout.scene5_2: res/layout/scene5_2.xml
  0x7f030040 (2130903104) = layout.scene5_3: res/layout/scene5_3.xml
  0x7f030041 (2130903105) = layout.search_layout_fragment: res/layout/search_layout_fragment.xml
  0x7f030042 (2130903106) = layout.setting_item: res/layout/setting_item.xml
  0x7f030043 (2130903107) = layout.share_main: res/layout/share_main.xml
  0x7f030044 (2130903108) = layout.support_simple_spinner_dropdown_item: res/layout/support_simple_spinner_dropdown_item.xml
  0x7f030045 (2130903109) = layout.tb_dialog_frame: res/layout/tb_dialog_frame.xml
  0x7f030046 (2130903110) = layout.tb_dialog_item: res/layout/tb_dialog_item.xml
  0x7f030047 (2130903111) = layout.tb_dialog_list_item_single_choice: res/layout/tb_dialog_list_item_single_choice.xml
  0x7f030048 (2130903112) = layout.tb_dialog_list_item_single_choice_cancel_order: res/layout/tb_dialog_list_item_single_choice_cancel_order.xml
  0x7f030049 (2130903113) = layout.tb_dialog_progress: res/layout/tb_dialog_progress.xml
  0x7f03004a (2130903114) = layout.tf_share_qrcode: res/layout/tf_share_qrcode.xml
  0x7f03004b (2130903115) = layout.uik_banner: res/layout/uik_banner.xml
  0x7f03004c (2130903116) = layout.uik_choice_divider: res/layout/uik_choice_divider.xml
  0x7f03004d (2130903117) = layout.uik_circular_progress: res/layout/uik_circular_progress.xml
  0x7f03004e (2130903118) = layout.uik_edit_multiple_choice: res/layout/uik_edit_multiple_choice.xml
  0x7f03004f (2130903119) = layout.uik_error: res/layout/uik_error.xml
  0x7f030050 (2130903120) = layout.uik_error_button: res/layout/uik_error_button.xml
  0x7f030051 (2130903121) = layout.uik_filter_tab: res/layout/uik_filter_tab.xml
  0x7f030052 (2130903122) = layout.uik_fragment_filter: res/layout/uik_fragment_filter.xml
  0x7f030053 (2130903123) = layout.uik_image_save_choice: res/layout/uik_image_save_choice.xml
  0x7f030054 (2130903124) = layout.uik_image_save_dialog: res/layout/uik_image_save_dialog.xml
  0x7f030055 (2130903125) = layout.uik_imageviewer_dialog: res/layout/uik_imageviewer_dialog.xml
  0x7f030056 (2130903126) = layout.uik_listitem_filter_child: res/layout/uik_listitem_filter_child.xml
  0x7f030057 (2130903127) = layout.uik_listitem_filter_group: res/layout/uik_listitem_filter_group.xml
  0x7f030058 (2130903128) = layout.uik_newbie_hint_fragment: res/layout/uik_newbie_hint_fragment.xml
  0x7f030059 (2130903129) = layout.uik_zoom_image: res/layout/uik_zoom_image.xml
  0x7f03005a (2130903130) = layout.uik_zoom_page_item: res/layout/uik_zoom_page_item.xml
  0x7f03005b (2130903131) = layout.uikit_search_view: res/layout/uikit_search_view.xml
  0x7f03005c (2130903132) = layout.update_coerce: res/layout/update_coerce.xml
  0x7f03005d (2130903133) = layout.update_notification: res/layout/update_notification.xml
  0x7f03005e (2130903134) = layout.weapp_tf_empty_page: res/layout/weapp_tf_empty_page.xml
  0x7f03005f (2130903135) = layout.welcome: res/layout/welcome.xml
  0x7f030060 (2130903136) = layout.welcome_frame: res/layout/welcome_frame.xml
  0x7f030061 (2130903137) = layout.wopc_auth_dialog: res/layout/wopc_auth_dialog.xml
  0x7f030062 (2130903138) = layout.wopc_auth_pop_window: res/layout/wopc_auth_pop_window.xml
  
上面是淘宝的资源 ，发现这么个问题，host的layout资源不少于插件的能启动
